spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dca_condo
    username: root
    password: root
    test-while-idle: true
    validation-query: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  data:
    rest:
      base-path: /
  mvc:
    locale: pt_BR
    date-format: dd/MM/yyyy
  thymeleaf:
    cache: false
